#+SETUPFILE: /home/krutna/.emacs.d/org-mode/itmo/main/setup.org
#+SETUPFILE: /home/krutna/.emacs.d/org-mode/orgs/setup/setup.org
#+BEGIN_CENTER
*Санкт-Петербургский Национальный Исследовательский*\\
*Университет Информационных Технологий, Механики и Оптики*\\
*Факультет Программной Инженерии и Компьютерной Техники*\\
#+END_CENTER
#+LATEX: \vspace{1em}
#+ATTR_LATEX: :width 120pt
#+ATTR_ORG: :width 120pt
file:./itmo-logo.png
#+LATEX: \LARGE
#+LATEX: \vspace{5em}
#+BEGIN_CENTER
*Вариант №824714*\\
*Лабораторная работа №1*\\
#+LATEX: \Large
*по дисциплине*\\
#+LATEX: \LARGE
*/'Программирование'/*\\
#+END_CENTER
#+LATEX: \vspace{11em}
#+LATEX: \large
#+LATEX: \begin{flushright}
*Выполнил:*\\
*Студент группы P3113*\\
*/Крутько Никита/ : 242570*\\
*Преподаватель:*\\
*/Письмак Алексей Евгеньевич/*\\
#+LATEX: \end{flushright}
#+LATEX: \vspace{4em}
#+LATEX: \large
#+BEGIN_CENTER
*Санкт-Петербург 2019 г.*
#+END_CENTER
#+LATEX: \pagebreak{}
**** Задание:
Написать программу на языке *Java*, выполняющую соответствующие варианту действия. Программа должна соответствовать следующим требованиям:
1. Она должна быть упакована в исполняемый jar-архив.
2. Выражение должно вычисляться в соответствии с правилами вычисления математи\-чес\-ких выражений (должен соблюдаться порядок выполнения действий и т.д.).
3. Программа должна использовать математические функции из стандартной биб\-лиотеки Java.
4. Результат вычисления выражения должен быть выведен в стандартный поток вывода в заданном формате.
Выполнение программы необходимо продемонстрировать на сервере *hellios*.

**** Исходный код:
#+LATEX: \small
#+ATTR_LATEX: :float nil
#+CAPTION: Main.java
#+INCLUDE: "../Main.java" src Java
**** Вывод программы:
#+LATEX: \fontsize{6}{8} \selectfont
#+BEGIN_SRC shell :exports results :results output
  cat ../output
#+END_SRC

#+RESULTS:
#+begin_example
   1,0247e+00   1,5154e+00  -1,0988e+00  -1,7137e-01  -9,8037e-01   7,6337e-01   1,0950e+00   1,6724e-02  -7,6277e-01   2,5500e-01
   1,1412e+00   8,4987e-01   1,3588e+00   1,4124e+00   1,0389e+00   8,0466e-01   1,5501e+00   1,5574e+00   1,0500e+00   1,4404e+00
   1,0247e+00   1,5154e+00  -1,0988e+00  -1,7137e-01  -9,8037e-01   7,6337e-01   1,0950e+00   1,6724e-02  -7,6277e-01   2,5500e-01
   7,3699e-01   7,8539e-01  -7,7968e-01   7,4927e-01   7,1027e-01   7,7508e-01  -7,7770e-01   7,7474e-01   5,4438e-01   7,8525e-01
   1,0247e+00   1,5154e+00  -1,0988e+00  -1,7137e-01  -9,8037e-01   7,6337e-01   1,0950e+00   1,6724e-02  -7,6277e-01   2,5500e-01
   1,1412e+00   8,4987e-01   1,3588e+00   1,4124e+00   1,0389e+00   8,0466e-01   1,5501e+00   1,5574e+00   1,0500e+00   1,4404e+00
   1,1412e+00   8,4987e-01   1,3588e+00   1,4124e+00   1,0389e+00   8,0466e-01   1,5501e+00   1,5574e+00   1,0500e+00   1,4404e+00
   1,0247e+00   1,5154e+00  -1,0988e+00  -1,7137e-01  -9,8037e-01   7,6337e-01   1,0950e+00   1,6724e-02  -7,6277e-01   2,5500e-01
   1,1412e+00   8,4987e-01   1,3588e+00   1,4124e+00   1,0389e+00   8,0466e-01   1,5501e+00   1,5574e+00   1,0500e+00   1,4404e+00
   1,1412e+00   8,4987e-01   1,3588e+00   1,4124e+00   1,0389e+00   8,0466e-01   1,5501e+00   1,5574e+00   1,0500e+00   1,4404e+00
#+end_example
\large
**** Вывод:
Я познакомился с языком *Java*, изучил некоторые библиотеки (*Math*), методы других классов, основные примитивные типы данных языка и их особенности. \\
Изучил некоторые основные параметры javac, java, jar, jdb и использовал их для сборки и написания программы. \\
Также изучил JDK и JRE: какие основные компоненты в них входят и их назначение.
